using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Axion.Scripting;

/// <summary>
/// Emits a complete C# class (subclassing Axion.Core.Behavior) from the shared AST.
/// The Roslyn-based ScriptHost compiles this into a .NET assembly at runtime.
/// </summary>
public static class CSharpEmitter
{
    public sealed class Options
    {
        /// <summary>Generated C# class name. Unity-style: PascalCase from filename.</summary>
        public string ClassName { get; set; } = "GeneratedScript";
        /// <summary>Namespace; defaults to "Axion.Scripts.Generated".</summary>
        public string Namespace { get; set; } = "Axion.Scripts.Generated";
        /// <summary>If true, emit as a Behavior subclass (engine script). Else, emit a static console-style class.</summary>
        public bool AsBehavior { get; set; } = true;
    }

    public static string Emit(ProgramNode p, Options? opts = null)
    {
        opts ??= new Options();
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/> Axion CSharpEmitter");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Numerics;");
        sb.AppendLine("using Axion.Core;");
        foreach (var s in p.Body) if (s is ImportStmt im) sb.AppendLine($"using {im.Path.Trim('"','\'')};");
        sb.AppendLine();
        sb.AppendLine($"namespace {opts.Namespace};");
        sb.AppendLine();

        var bodyStmts  = p.Body.Where(s => s is not FuncDecl && s is not ImportStmt && s is not CommentStmt).ToList();
        var funcs      = p.Body.OfType<FuncDecl>().ToList();
        bool hasStart  = funcs.Any(f => f.Name.Equals("start", System.StringComparison.OrdinalIgnoreCase));
        bool hasUpdate = funcs.Any(f => f.Name.Equals("loop",  System.StringComparison.OrdinalIgnoreCase) ||
                                          f.Name.Equals("update",System.StringComparison.OrdinalIgnoreCase));

        if (opts.AsBehavior)
        {
            sb.AppendLine($"public sealed class {opts.ClassName} : Behavior");
            sb.AppendLine("{");
            // Inline top-level statements as Awake() body when there is no explicit start/loop:
            if (!hasStart && !hasUpdate && bodyStmts.Count > 0)
            {
                sb.AppendLine("    public override void Start()");
                sb.AppendLine("    {");
                foreach (var s in bodyStmts) EmitStmt(s, 2, sb);
                sb.AppendLine("    }");
            }
            else if (bodyStmts.Count > 0)
            {
                // Top-level VarDecls become private fields (visible to Start/Update/etc),
                // everything else (assignments, calls, ifs, …) runs in Awake().
                // This matches Unity's mental model: `speed = 90` at file scope is a
                // member of the script, not a local of one method.
                var fields    = bodyStmts.OfType<VarDecl>().ToList();
                var awakeBody = bodyStmts.Where(s => s is not VarDecl).ToList();
                foreach (var v in fields) EmitFieldDecl(v, sb);
                if (awakeBody.Count > 0)
                {
                    if (fields.Count > 0) sb.AppendLine();
                    sb.AppendLine("    public override void Awake()");
                    sb.AppendLine("    {");
                    foreach (var s in awakeBody) EmitStmt(s, 2, sb);
                    sb.AppendLine("    }");
                }
            }

            foreach (var f in funcs)
            {
                var nm = f.Name.ToLowerInvariant();
                bool isStart  = nm == "start";
                bool isUpdate = nm == "loop" || nm == "update";
                sb.AppendLine();
                if (isStart)
                {
                    sb.AppendLine("    public override void Start()");
                    sb.AppendLine("    {");
                    foreach (var s in f.Body) EmitStmt(s, 2, sb);
                    sb.AppendLine("    }");
                }
                else if (isUpdate)
                {
                    sb.AppendLine("    public override void Update()");
                    sb.AppendLine("    {");
                    foreach (var s in f.Body) EmitStmt(s, 2, sb);
                    sb.AppendLine("    }");
                }
                else
                {
                    var pars = string.Join(", ", f.Params.Select(p => "dynamic " + p));
                    sb.AppendLine($"    private dynamic {f.Name}({pars})");
                    sb.AppendLine("    {");
                    foreach (var s in f.Body) EmitStmt(s, 2, sb);
                    sb.AppendLine("        return null;");
                    sb.AppendLine("    }");
                }
            }
            sb.AppendLine("}");
        }
        else
        {
            sb.AppendLine($"public static class {opts.ClassName}");
            sb.AppendLine("{");
            sb.AppendLine("    public static void Main(string[] args)");
            sb.AppendLine("    {");
            foreach (var s in bodyStmts) EmitStmt(s, 2, sb);
            sb.AppendLine("    }");
            foreach (var f in funcs)
            {
                var pars = string.Join(", ", f.Params.Select(p => "dynamic " + p));
                sb.AppendLine($"    static dynamic {f.Name}({pars})");
                sb.AppendLine("    {");
                foreach (var s in f.Body) EmitStmt(s, 2, sb);
                sb.AppendLine("        return null;");
                sb.AppendLine("    }");
            }
            sb.AppendLine("}");
        }
        return sb.ToString();
    }

    private static string Ind(int n) => new(' ', n * 4);

    /// <summary>
    /// Emit a top-level Gel VarDecl as a private instance field on the generated
    /// Behavior class.  <c>var</c> isn't legal for fields, so we widen it to
    /// <c>dynamic</c> when the type is unknown.
    /// </summary>
    private static void EmitFieldDecl(VarDecl v, StringBuilder sb)
    {
        var rhs = EmitExpr(v.Value!);
        var ty  = !string.IsNullOrEmpty(v.Type) ? v.Type : InferType(v.Value);
        if (ty == "var") ty = "dynamic";
        sb.AppendLine($"    private {ty} {v.Name} = {rhs};");
    }

    private static void EmitStmt(Stmt s, int lvl, StringBuilder sb)
    {
        var ind = Ind(lvl);
        switch (s)
        {
            case CommentStmt c:  sb.AppendLine($"{ind}// {c.Text}"); break;
            case ImportStmt:     break;
            case VarDecl v:
            {
                var rhs = EmitExpr(v.Value!);
                var ty  = !string.IsNullOrEmpty(v.Type) ? v.Type : InferType(v.Value);
                sb.AppendLine($"{ind}{ty} {v.Name} = {rhs};"); break;
            }
            case Assign a:       sb.AppendLine($"{ind}{EmitExpr(a.Target)} = {EmitExpr(a.Value)};"); break;
            case ExprStmt es:    sb.AppendLine($"{ind}{EmitExpr(es.Expr)};"); break;
            case ReturnStmt r:   sb.AppendLine($"{ind}return{(r.Values.Count > 0 ? " " + EmitExpr(r.Values[0]) : "")};"); break;
            case BreakStmt:      sb.AppendLine($"{ind}break;"); break;
            case ContinueStmt:   sb.AppendLine($"{ind}continue;"); break;
            case CrashStmt cr:   sb.AppendLine($"{ind}throw new Exception({(cr.Reason != null ? EmitExpr(cr.Reason) : "\"crash\"")});"); break;
            case IfStmt iff:
                sb.AppendLine($"{ind}if ({EmitExpr(iff.Cond)})");
                sb.AppendLine($"{ind}{{");
                foreach (var t in iff.Then) EmitStmt(t, lvl + 1, sb);
                sb.AppendLine($"{ind}}}");
                foreach (var (ec, eb) in iff.Elifs)
                {
                    sb.AppendLine($"{ind}else if ({EmitExpr(ec)})");
                    sb.AppendLine($"{ind}{{");
                    foreach (var t in eb) EmitStmt(t, lvl + 1, sb);
                    sb.AppendLine($"{ind}}}");
                }
                if (iff.Else != null) { sb.AppendLine($"{ind}else"); sb.AppendLine($"{ind}{{"); foreach (var t in iff.Else) EmitStmt(t, lvl + 1, sb); sb.AppendLine($"{ind}}}"); }
                break;
            case WhileStmt w:
                sb.AppendLine($"{ind}while ({EmitExpr(w.Cond)})");
                sb.AppendLine($"{ind}{{");
                foreach (var t in w.Body) EmitStmt(t, lvl + 1, sb);
                sb.AppendLine($"{ind}}}"); break;
            case LoopStmt lp:
                sb.AppendLine($"{ind}while (true)");
                sb.AppendLine($"{ind}{{");
                foreach (var t in lp.Body) EmitStmt(t, lvl + 1, sb);
                sb.AppendLine($"{ind}}}"); break;
            case ForStmt f:
            {
                string init = f.Init is VarDecl iv ? $"int {iv.Name} = {EmitExpr(iv.Value!)}" : "";
                string step = f.Step is VarDecl sv ? $"{sv.Name} = {EmitExpr(sv.Value!)}" : "";
                string cond = f.Cond != null ? EmitExpr(f.Cond) : "true";
                sb.AppendLine($"{ind}for ({init}; {cond}; {step})");
                sb.AppendLine($"{ind}{{");
                foreach (var t in f.Body) EmitStmt(t, lvl + 1, sb);
                sb.AppendLine($"{ind}}}"); break;
            }
            case ForEachStmt fe:
                sb.AppendLine($"{ind}foreach (var {fe.VarName} in {EmitExpr(fe.Iterable)})");
                sb.AppendLine($"{ind}{{");
                foreach (var t in fe.Body) EmitStmt(t, lvl + 1, sb);
                sb.AppendLine($"{ind}}}"); break;
            case MatchStmt m:
                sb.AppendLine($"{ind}switch ({EmitExpr(m.Subject)})");
                sb.AppendLine($"{ind}{{");
                foreach (var (pat, body) in m.Cases)
                {
                    sb.AppendLine($"{ind}    case var __c when __c.Equals({EmitExpr(pat)}):");
                    foreach (var t in body) EmitStmt(t, lvl + 2, sb);
                    sb.AppendLine($"{ind}        break;");
                }
                if (m.Else != null) { sb.AppendLine($"{ind}    default:"); foreach (var t in m.Else) EmitStmt(t, lvl + 2, sb); sb.AppendLine($"{ind}        break;"); }
                sb.AppendLine($"{ind}}}"); break;
        }
    }

    private static string EmitExpr(Expr e) => e switch
    {
        NumLit n => n.Value.Contains('.') ? n.Value + "f" : n.Value,
        StrLit s => s.Value,
        BoolLit b => b.Value ? "true" : "false",
        NullLit => "null",
        VarRef v => MapBuiltin(v.Name),
        BinOp b when b.Op == "^" => $"(float)Math.Pow({EmitExpr(b.Left)}, {EmitExpr(b.Right)})",
        BinOp b => $"({EmitExpr(b.Left)} {b.Op} {EmitExpr(b.Right)})",
        UnaryOp u => $"{u.Op}{EmitExpr(u.Operand)}",
        CallExpr c => EmitCall(c),
        MemberExpr m => $"{EmitExpr(m.Target)}.{MapMember(m.Target, m.Member)}",
        IndexExpr ix => $"{EmitExpr(ix.Target)}[{EmitExpr(ix.Index)}]",
        ListLit l => $"new List<dynamic>{{ {string.Join(", ", l.Items.Select(EmitExpr))} }}",
        RangeExpr r => $"Enumerable.Range({EmitExpr(r.Start)}, ({EmitExpr(r.End)}) - ({EmitExpr(r.Start)}))",
        _ => "/*expr*/",
    };

    /// <summary>
    /// Translate Gel-style snake/camelCase member names into the engine's PascalCase
    /// API names when the target is a known engine root (transform, gameObject, time, …).
    /// Pass-through for anything else.
    /// </summary>
    private static string MapMember(Expr target, string name)
    {
        if (target is not VarRef vr) return name;
        return (vr.Name, name) switch
        {
            // transform.* (this.Transform)
            ("transform", "position")      => "Position",
            ("transform", "rotation")      => "Rotation",
            ("transform", "scale")         => "LocalScale",
            ("transform", "localPosition") => "LocalPosition",
            ("transform", "localRotation") => "LocalRotation",
            ("transform", "localScale")    => "LocalScale",
            ("transform", "eulerAngles")   => "EulerAngles",
            ("transform", "forward")       => "Forward",
            ("transform", "right")         => "Right",
            ("transform", "up")            => "Up",
            ("transform", "parent")        => "Parent",
            ("transform", "children")      => "Children",
            // gameObject.* (this.GameObject)
            ("gameObject", "name")         => "Name",
            ("gameObject", "active")       => "Active",
            ("gameObject", "transform")    => "Transform",
            ("gameObject", "tag")          => "Tag",
            // time.* (Axion.Core.Time)
            ("time", "delta")              => "DeltaTime",
            ("time", "deltaTime")          => "DeltaTime",
            ("time", "elapsed")            => "ElapsedTime",
            ("time", "elapsedTime")        => "ElapsedTime",
            ("time", "frame")              => "FrameCount",
            ("time", "frames")             => "FrameCount",
            ("time", "scale")              => "TimeScale",
            ("time", "fixedDelta")         => "FixedDelta",
            // input.mouse.* (Axion.Core.Input)
            ("mouse", "position")          => "MousePosition",
            ("mouse", "delta")             => "MouseDelta",
            ("mouse", "scroll")            => "ScrollDelta",
            _ => name,
        };
    }

    private static string EmitCall(CallExpr c)
    {
        if (c.Callee is VarRef v)
        {
            switch (v.Name)
            {
                case "print":          return $"Log.Info({Args(c.Args)})";
                case "rem":            return $"({EmitExpr(c.Args[0])} % {EmitExpr(c.Args[1])})";
                case "percent":        return $"({EmitExpr(c.Args[0])} / 100f * {EmitExpr(c.Args[1])})";
                case "convert":        return $"Convert.ChangeType({EmitExpr(c.Args[0])}, typeof({EmitExpr(c.Args[1])}))";
                case "quit":           return $"throw new Exception({(c.Args.Count > 0 ? EmitExpr(c.Args[0]) : "\"quit\"")})";
                // ── Game-engine helpers ─────────────────────────────────────────
                case "vec3":           return $"new Vector3({F(c, 0)}, {F(c, 1)}, {F(c, 2)})";
                case "vec2":           return $"new Vector2({F(c, 0)}, {F(c, 1)})";
                case "find":           return $"(Axion.Engine.AxionApp.Instance!.Scene.Find({EmitExpr(c.Args[0])}))";
                case "destroy":        return $"(Axion.Engine.AxionApp.Instance!.Scene.Remove({EmitExpr(c.Args[0])}))";
                case "instantiate":    return $"(Axion.Engine.AxionApp.Instance!.Scene.CreateGameObject({EmitExpr(c.Args[0])}))";
            }
        }
        if (c.Callee is MemberExpr me && me.Target is VarRef vt && vt.Name == "print")
        {
            return me.Member switch
            {
                "console" => $"Console.WriteLine({Args(c.Args)})",
                "log"     => $"Log.Info({Args(c.Args)})",
                _         => $"Log.Info({Args(c.Args)})",
            };
        }
        // ── Gel input.* family → Axion.Core.Input ─────────────────────────────
        // Maps the standard Gel input system onto the engine's frame-stable
        // keyboard / mouse pump.  Lets the same .gel script work both in the
        // standalone `gel` CLI and inside the engine.
        if (c.Callee is MemberExpr im && im.Target is VarRef ivt && ivt.Name == "input")
        {
            string KeyArg() => $"(Axion.Core.Key)System.Enum.Parse(typeof(Axion.Core.Key), {EmitExpr(c.Args[0])}, true)";
            return im.Member switch
            {
                "line"        => "(Console.ReadLine() ?? string.Empty)",
                "number"      => "(double.TryParse(Console.ReadLine() ?? string.Empty, out var __v) ? __v : double.NaN)",
                "int"         => "(long.TryParse(Console.ReadLine() ?? string.Empty, out var __i) ? __i : 0L)",
                "bool"        => "((Console.ReadLine() ?? string.Empty).Trim().ToLowerInvariant() is \"y\" or \"yes\" or \"true\" or \"1\" or \"on\")",
                "key"         => "Console.ReadKey(true).KeyChar.ToString().ToUpperInvariant()",
                "keyDown"     => $"Axion.Core.Input.GetKeyDown({KeyArg()})",
                "keyPressed"  => $"Axion.Core.Input.GetKeyDown({KeyArg()})",
                "keyReleased" => $"Axion.Core.Input.GetKeyUp({KeyArg()})",
                "axis"        => $"Axion.Core.Input.GetAxis({EmitExpr(c.Args[0])})",
                _             => "(Console.ReadLine() ?? string.Empty)",
            };
        }
        if (c.Callee is VarRef iv && iv.Name == "input")
        {
            // input("prompt")  → write prompt then read a line
            return c.Args.Count > 0
                ? $"((Action)(() => Console.Write({EmitExpr(c.Args[0])}))).Invoke() == null ? (Console.ReadLine() ?? string.Empty) : string.Empty"
                : "(Console.ReadLine() ?? string.Empty)";
        }

        // ── Game-engine member calls ─────────────────────────────────────────────
        // transform.translate(x,y,z) / .rotate(x,y,z) / .lookAt(target) / .scaleBy(s)
        if (c.Callee is MemberExpr tm && tm.Target is VarRef tvr && tvr.Name == "transform")
        {
            return tm.Member switch
            {
                "translate" => $"(this.Transform.Position = this.Transform.Position + new Vector3({F(c,0)}, {F(c,1)}, {F(c,2)}))",
                "rotate"    => $"(this.Transform.EulerAngles = this.Transform.EulerAngles + new Vector3({F(c,0)}, {F(c,1)}, {F(c,2)}))",
                "lookAt"    => $"(this.Transform.LookAt({EmitExpr(c.Args[0])}))",
                "setPosition" => $"(this.Transform.Position = new Vector3({F(c,0)}, {F(c,1)}, {F(c,2)}))",
                "setScale"  => $"(this.Transform.LocalScale = new Vector3({F(c,0)}, {F(c,1)}, {F(c,2)}))",
                _ => $"this.Transform.{tm.Member}({Args(c.Args)})",
            };
        }
        // log.info / log.warn / log.error
        if (c.Callee is MemberExpr lm && lm.Target is VarRef lvr && lvr.Name == "log")
        {
            return lm.Member switch
            {
                "info"  => $"Axion.Core.Log.Info({Args(c.Args)})",
                "warn"  => $"Axion.Core.Log.Warn({Args(c.Args)})",
                "error" => $"Axion.Core.Log.Error({Args(c.Args)})",
                _       => $"Axion.Core.Log.Info({Args(c.Args)})",
            };
        }
        // random.value() / random.range(a,b) / random.int(a,b)
        if (c.Callee is MemberExpr rm && rm.Target is VarRef rvr && rvr.Name == "random")
        {
            return rm.Member switch
            {
                "value"  => "(float)System.Random.Shared.NextDouble()",
                "range"  => $"((float)(System.Random.Shared.NextDouble() * (({F(c,1)}) - ({F(c,0)})) + ({F(c,0)})))",
                "int"    => $"System.Random.Shared.Next((int)({F(c,0)}), (int)({F(c,1)}))",
                "sign"   => "(System.Random.Shared.Next(2) == 0 ? -1f : 1f)",
                _        => "(float)System.Random.Shared.NextDouble()",
            };
        }
        // scene.find(name) / scene.create(name)
        if (c.Callee is MemberExpr sm && sm.Target is VarRef svr && svr.Name == "scene")
        {
            return sm.Member switch
            {
                "find"   => $"(Axion.Engine.AxionApp.Instance!.Scene.Find({EmitExpr(c.Args[0])}))",
                "create" => $"(Axion.Engine.AxionApp.Instance!.Scene.CreateGameObject({EmitExpr(c.Args[0])}))",
                "remove" => $"(Axion.Engine.AxionApp.Instance!.Scene.Remove({EmitExpr(c.Args[0])}))",
                _        => $"Axion.Engine.AxionApp.Instance!.Scene.{sm.Member}({Args(c.Args)})",
            };
        }

        return $"{EmitExpr(c.Callee)}({Args(c.Args)})";
    }

    /// <summary>Emit the n-th call argument coerced to <c>float</c> for Vector math.</summary>
    private static string F(CallExpr c, int i)
        => i < c.Args.Count ? $"(float)({EmitExpr(c.Args[i])})" : "0f";

    private static string Args(List<Expr> args) => string.Join(", ", args.Select(EmitExpr));

    private static string MapBuiltin(string name) => name switch
    {
        "true"  => "true",
        "false" => "false",
        "null" or "none" => "null",
        // Engine roots — make `transform.position`, `time.delta`, etc resolve naturally
        // inside a generated Behavior subclass.
        "transform"  => "this.Transform",
        "gameObject" => "this.GameObject",
        "self"       => "this",
        "time"       => "Axion.Core.Time",
        "scene"      => "Axion.Engine.AxionApp.Instance!.Scene",
        "app"        => "Axion.Engine.AxionApp.Instance",
        "mouse"      => "Axion.Core.Input",
        _ => name,
    };

    private static string InferType(Expr? v) => v switch
    {
        NumLit n => n.Value.Contains('.') ? "float" : "int",
        StrLit  => "string",
        BoolLit => "bool",
        ListLit => "List<dynamic>",
        _ => "var",
    };
}
